#!/bin/bash
# Vast.ai GPU Workflow Guide
# This script shows the commands - run them manually

echo "=== VAST.AI GPU WORKFLOW ==="
echo ""

echo "1. SETUP (one time only)"
echo "   ./scripts/setup_ssh.sh"
echo ""

echo "2. SEARCH for GPUs"
echo "   # Find cheapest GPUs"
echo "   python cli.py search --max-price 0.05"
echo ""
echo "   # Find best value (price + power)"
echo "   python cli.py search --max-price 0.10 --order-by price_power"
echo ""
echo "   # Filter by VRAM"
echo "   python cli.py search --min-gpu-ram 12 --max-price 0.10"
echo ""

echo "3. LAUNCH an instance"
echo "   # Basic launch with PyTorch image"
echo "   python cli.py launch --gpu 'RTX 3060' --image pytorch"
echo ""
echo "   # With more disk space"
echo "   python cli.py launch --gpu 'RTX 3060' --disk 50"
echo ""
echo "   # With custom command on start"
echo "   python cli.py launch --gpu 'RTX 3060' --onstart 'pip install transformers'"
echo ""

echo "4. MANAGE instances"
echo "   # List your instances"
echo "   python cli.py list"
echo ""
echo "   # Get SSH command"
echo "   python cli.py ssh <instance_id>"
echo ""
echo "   # Stop instance (saves money, keeps data)"
echo "   python cli.py stop <instance_id>"
echo ""
echo "   # Start stopped instance"
echo "   python cli.py start <instance_id>"
echo ""
echo "   # Destroy instance (deletes everything)"
echo "   python cli.py destroy <instance_id>"
echo ""

echo "5. CONNECT via SSH"
echo "   ssh -i keys/vast_gpu -p <port> root@<host>"
echo ""
echo "   # Or use the ssh command from 'python cli.py ssh <id>'"
echo ""

echo "=== TIPS ==="
echo "- Instances charge per hour while running"
echo "- Stop instances when not using them"
echo "- Data is lost when you destroy an instance"
echo "- Use --json flag for scripting"
